[workspace]
members = ["programs/hoshi-kya"]
resolver = "2"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
hoshi_kya = "7QaaaMxxPavk8KRZwS5WwbPzPmRkXPtjFmfxh2M8ev1Z"
